upstream auth_service { 
    server auth-service:8001; 
}
upstream item_service { 
    server item-service:8002; 
}
upstream frontend_service { 
    server frontend:80; 
}

server {
    listen 80;
    server_name localhost;

    # 1. Frontend Route (Catch-all - taruh di paling bawah secara logika)
    location / {
        proxy_pass http://frontend_service;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # 2. API Routes
    location /auth/ {
        proxy_pass http://auth_service/;
        proxy_set_header Host $host;
    }

    location /api/items {
        proxy_pass http://item_service/items;
        proxy_set_header Host $host;
    }

    # 3. Monitoring (Health & Metrics - Wajib untuk StatusPage)
    location /health {
        default_type application/json;
        return 200 '{"status": "healthy", "service": "gateway"}';
    }
    
    location /auth/health { proxy_pass http://auth_service/health; }
    location /auth/metrics { proxy_pass http://auth_service/metrics; }
    location /items/health { proxy_pass http://item_service/health; }
    location /items/metrics { proxy_pass http://item_service/metrics; }
}